### ISSUE TITLE
Please tell me how to receive the data continuously.

### ISSUE THREAD

**Issue by junboonge** [Kawoogie/MAXM86161_Library#1]
Hello, thank you for sharing the code. 
Below is a code written using your code.

```
int main()
{   
    int red,green,ir,ambient,cnt;
     // Initialize the sensor with default values
    ppg.init();
    ppg.set_interrogation_rate(PPG_SR_1024);
    ppg.set_ppg_tint(0x2);
    ppg.set_sample_averaging(0x2);
    ppg.start();
    ThisThread::sleep_for(10ms);
    ppg.read(red, green, ir, ambient);
    ThisThread::sleep_for(10ms);
    while (true) {
        ppg.new_value_read_on();
        ppg.read(red, green, ir, ambient);
        ThisThread::sleep_for(1ms);
        printf("%d\n",green);
        ppg.new_value_read_off();
        // Stop the device
    }
    ppg.stop();
        // Wait with the device off
}
```

This code is used to obtain data, but it does not output as much as the sampling frequency.

Is there a way to get data as continuously as sampling frequency?

**Comment by Kawoogie** [comment]
Hello. Yes, you are correct in that this code will not update with the sampling frequency. 

The best way to do that is to use the interrupt pin on the chip, which is connected to pad 14. This interrupt goes low when the interrupt has been triggered. You can set what triggers the interrupt on register 0x02 on the MAXM86161. It can be configured to trigger when a set number of samples is stored in the FIFO by setting bit 7 to 1. If you want the interrupt to trigger any time there is new data to read, you can set bit 6 to 1 of register 0x02. 
You will then have to program your micro-controller to trigger on the interrupt in by looking for it to go low. You will also need to use a pullup resistor as well.

**Comment by junboonge** [comment]
I solved this problem by creating a new read function. I think the method you told me is also a good way. Thank you for your answer.
